# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 020b5b416df54b0565fc7371d6ad5f2e8ebc1dfe66601b8299f6f2d0d2c38ebab58596298b475151ac8398c7b37ae9c3db32c90964ce285006c7efc6a9c8a0bd

test:
  secret_key_base: 400b14df750ba9f1af9e5c2fc0f2361b0079e6c03f0c246887874b7612cfbd79b1e020d525f649ec5ae7dcc102021ab74a422e26e83c41080f2712f32505c138

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
